### PR TITLE
Add `to_angle` for the `Rot2` class

### PR DESCRIPTION
**Pull request by hflemmen**
I suggest adding a convenience function to get the angle from a 2D rotation. It complements the existing `from_angle`, and is intuitive to use when working with 2D rotation angles.

### CODE REVIEW

File: symforce/geo/rot2.py [hunk 1]
```diff
@@ -137,6 +137,14 @@ def from_angle(cls, theta: T.Scalar) -> Rot2:
         """
         return cls.from_tangent([theta])
 
+    def to_angle(self, epsilon=sf.epsilon()) -> T.Scalar:
+        """
+        Get the angle of this Rot2 in radians
+
+        This is equivalent to ``to_tangent()[0]``
+        """
+        return sf.atan2(self.z.imag, self.z.real, epsilon=epsilon)
```
Comment (aaron-skydio) [inline symforce/geo/rot2.py:146]: I think this should just call `to_tangent` to avoid duplicating the implementation, like `from_angle` does with `from_tangent`

**Review by aaron-skydio — COMMENTED** [review]
Cool, yeah I think this is a good thing to have

File: symforce/geo/rot2.py (hunk 1 above)
Comment (hflemmen) [reply symforce/geo/rot2.py]: That makes sense, I changed it now.

**Comment by hflemmen** [comment]
It seems like it fails the lint checks. Do you have a special linter format?

**Comment by aaron-skydio** [comment]
You need a type annotation for `epsilon: T.Scalar`:
```
symforce/geo/rot2.py:140: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
```

You can run the linter with `make lint` (it's just black, mypy, and pylint with the configurations in pyproject.toml and pylintrc)

**Comment by hflemmen** [comment]
Thank you for the explanation. `make lint` did not work for me, possibly due to the issue with python 3.10.7, which is mentioned in the test case. I added the scalar type for `epsilon`.

**Comment by aaron-skydio** [comment]
Looks like the thing that's failing now is the autoformat - `make format` should work fine on py3.10, or you can just copy-paste the suggested change

**Comment by hflemmen** [comment]
`make format` changed a lot of files that I have not touched. Should I commit those as well?

**Comment by hflemmen** [comment]
True, i used `black` version `23.7.0`.

There are rather many files that are affected, but mostly for the same reasons:

- Add spaces around `**` operators.
- Remove blank line after `:`.
- Remove parenthesis around tuples in for loops. E.g. `for (expr, name) in self.override_methods.items():` -> `for expr, name in self.override_methods.items():`

After revering to the correct version of `black`, the two latter ones were not undone, so I guess that it accepts both versions.

**Comment by hflemmen** [comment]
Now that all checks have passed, is there more I need to do before the review is passed and it can be merged?

**Comment by aaron-skydio** [comment]
> 

Thanks, makes sense

> Now that all checks have passed, is there more I need to do before the review is passed and it can be merged?

Nothing more you need to do, I'll merge it

**Review by aaron-skydio — APPROVED** [review]
